My ip2
Arty2018/WallOfSound pull request #2
Opened 2018-04-08 22:35 UTC by Arty2018

bastion_current_ip.py has been edited to accept command line options as follows:

  -k SSH_KEY_NAME, --ssh_key_name SSH_KEY_NAME
  -s SUBNET_LIST, --subnet_list SUBNET_LIST
  -n NAME, --name NAME
  -z ZONE_NAME, --zone_name ZONE_NAME
  -r REGION, --region REGION
  --destroy
  --plan_destroy
  --plan_apply
  --apply

2018-04-10 06:34 UTC, bknelson requested changes

2018-04-10 06:34 UTC, bknelson commented on bastion_current_ip.py
> +	parser.add_argument('-k','--ssh_key_name', type=str)
For each of these arguments, add a 'help' field

2018-04-10 06:34 UTC, bknelson commented on bastion_current_ip.py
> +# obtain current public ip, create a variables.tfvars file
Run this through a linter, so your code is consistant with PEP8 standard.  I suggest pylint.

2018-04-10 06:34 UTC, bknelson commented on bastion_current_ip.py
> +	except:
Can you be more specific about the exceptions you are catching?

2018-04-10 06:34 UTC, bknelson commented on bastion_current_ip.py
> +		except:
Can you be more specific about the exceptions you are catching?

2018-04-10 06:34 UTC, bknelson commented on bastion_current_ip.py
> +			myip = raw_input('Error obtaining IP address. Please specify IP: ')
Why not throw an exception with extra info?

2018-05-11 00:11 UTC, Arty2018 commented
@bknelson  please see latest commit for changes implemented

2018-05-11 04:58 UTC, bknelson approved these changes
:shipit:

2018-05-13 01:31 UTC, merged